import MainLayout from "./components/MainLayout";
import "./globals.css";
import Vazir from "next/font/local";
import "react-loading-skeleton/dist/skeleton.css";
const vazir = Vazir({
  src: "./Vazir.woff2",
  display: "swap",
});

export const metadata = {
  title: "Quiz App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="fa" dir="rtl">
      <body className={vazir.className}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
